# Numpy
[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/davemor/scientific-python-tutorial/blob/master/PythonTutorialPart2-Numpy.ipynb)

## Getting started

* Numpy is a huge package
* Most packages for data science build on numpy
* Documentation and further tutorials: https://numpy.org/doc/stable/

### Importing numpy

By convention:

Hello this is some more text.

In [39]:
import numpy as np

### Numpy arrays

Arrays are the basic objects in numpy.

An array is a multidimensional collection of data of the same type.

Arrays in numpy are referred to as ndarrays - for n dimensional array

**Creating arrays**

Basic syntax: *numpy.array(object, dtype=None)*

lets create an array of the integers 1 to 3

In [40]:
np.array([1,2,3])

array([1, 2, 3])

Alternatively as floating point numbers

In [41]:
arr = np.array([1,2,3], dtype=float)
arr

array([1., 2., 3.])

**Properties of arrays**

All arrays have a shape and a datatype.

These can be found using *ndarray.shape* *ndarray.dtype*

In [42]:
arr.shape

(3,)

In [43]:
arr.dtype

dtype('float64')

Create a 2 rows by 2 columns array of zeros

Create a 3 rows by 4 columns array of ones

In [44]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [45]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Create a 2 by 2 array of fours
* Create a 2 by 2 array
* Fill the array with the value 4

In [46]:
arr = np.empty((2, 2))
arr

array([[0., 0.],
       [0., 0.]])

In [47]:
arr.fill(4)
arr

array([[4., 4.],
       [4., 4.]])

## Reading / Writing data files

You have been provided with a csv file theoph.csv

In [48]:
theoph_file_location = 'theoph.csv'
theoph = np.genfromtxt(theoph_file_location, delimiter=',')
theoph

array([[  nan,   nan,   nan,   nan,   nan],
       [11.  , 79.6 ,  4.02,  0.  ,  0.74],
       [11.  , 79.6 ,  4.02,  0.25,  2.84],
       [11.  , 79.6 ,  4.02,  0.57,  6.57],
       [11.  , 79.6 ,  4.02,  1.12, 10.5 ],
       [11.  , 79.6 ,  4.02,  2.02,  9.66],
       [11.  , 79.6 ,  4.02,  3.82,  8.58],
       [11.  , 79.6 ,  4.02,  5.1 ,  8.36],
       [11.  , 79.6 ,  4.02,  7.03,  7.47],
       [11.  , 79.6 ,  4.02,  9.05,  6.89],
       [11.  , 79.6 ,  4.02, 12.12,  5.94],
       [11.  , 79.6 ,  4.02, 24.37,  3.28],
       [ 6.  , 72.4 ,  4.4 ,  0.  ,  0.  ],
       [ 6.  , 72.4 ,  4.4 ,  0.27,  1.72],
       [ 6.  , 72.4 ,  4.4 ,  0.52,  7.91],
       [ 6.  , 72.4 ,  4.4 ,  1.  ,  8.31],
       [ 6.  , 72.4 ,  4.4 ,  1.92,  8.33],
       [ 6.  , 72.4 ,  4.4 ,  3.5 ,  6.85],
       [ 6.  , 72.4 ,  4.4 ,  5.02,  6.08],
       [ 6.  , 72.4 ,  4.4 ,  7.03,  5.4 ],
       [ 6.  , 72.4 ,  4.4 ,  9.  ,  4.55],
       [ 6.  , 72.4 ,  4.4 , 12.  ,  3.01],
       [ 6.  , 72.4 ,  4.4 , 24.

Numpy arrays contain data of the same type

The first line in our csv file contains strings for the column names

Numpy has read those in as nan

*skip_header* arguement can be used to ignore lines at the start of a file

In [49]:
theoph = np.genfromtxt(theoph_file_location, delimiter=',', skip_header=1)
theoph

array([[11.  , 79.6 ,  4.02,  0.  ,  0.74],
       [11.  , 79.6 ,  4.02,  0.25,  2.84],
       [11.  , 79.6 ,  4.02,  0.57,  6.57],
       [11.  , 79.6 ,  4.02,  1.12, 10.5 ],
       [11.  , 79.6 ,  4.02,  2.02,  9.66],
       [11.  , 79.6 ,  4.02,  3.82,  8.58],
       [11.  , 79.6 ,  4.02,  5.1 ,  8.36],
       [11.  , 79.6 ,  4.02,  7.03,  7.47],
       [11.  , 79.6 ,  4.02,  9.05,  6.89],
       [11.  , 79.6 ,  4.02, 12.12,  5.94],
       [11.  , 79.6 ,  4.02, 24.37,  3.28],
       [ 6.  , 72.4 ,  4.4 ,  0.  ,  0.  ],
       [ 6.  , 72.4 ,  4.4 ,  0.27,  1.72],
       [ 6.  , 72.4 ,  4.4 ,  0.52,  7.91],
       [ 6.  , 72.4 ,  4.4 ,  1.  ,  8.31],
       [ 6.  , 72.4 ,  4.4 ,  1.92,  8.33],
       [ 6.  , 72.4 ,  4.4 ,  3.5 ,  6.85],
       [ 6.  , 72.4 ,  4.4 ,  5.02,  6.08],
       [ 6.  , 72.4 ,  4.4 ,  7.03,  5.4 ],
       [ 6.  , 72.4 ,  4.4 ,  9.  ,  4.55],
       [ 6.  , 72.4 ,  4.4 , 12.  ,  3.01],
       [ 6.  , 72.4 ,  4.4 , 24.3 ,  0.9 ],
       [ 5.  , 70.5 ,  4.53,  0.

To write files using numpy:

In [50]:
theoph_out_file = 'theoph_out.csv'
np.savetxt(theoph_out_file, theoph, delimiter=",")

**About theoph.csv**

This contains data from a study by Dr. Robert Upton of the kinetics of the anti-asthmatic drug theophylline [1]. 

Subjects were given oral doses of theophylline then serum concentrations were measured at 11 time points over the next 25 hours.

The columns of the data are: 

* Subject, a reference number identifying each subject (1 to 12)
* Wt, weight of the subject in kg
* Dose, dose of theophylline given to the subject in mg/kg
* Time, time since the drug was administered when the sample was drawn in hours
* conc, theophylline concentration in mg/L

[1] *Boeckmann, A. J., Sheiner, L. B. and Beal, S. L. (1994), NONMEM Users Guide: Part V, NONMEM Project Group, University of California, San Francisco.*

## Indexing and slicing

Indexing and slicing works similarly to base python and to R

Now we have multiple dimensions

### Indexing

Indexing is ndarray[row, column] *don't forget python is zero indexed*

So to get the value in the first row and column: 


In [51]:
theoph[0, 0]

11.0

To get all the values in the first row

In [52]:
theoph[0, :]

array([11.  , 79.6 ,  4.02,  0.  ,  0.74])

To get all the values in the last column

In [53]:
theoph[:, -1]

array([ 0.74,  2.84,  6.57, 10.5 ,  9.66,  8.58,  8.36,  7.47,  6.89,
        5.94,  3.28,  0.  ,  1.72,  7.91,  8.31,  8.33,  6.85,  6.08,
        5.4 ,  4.55,  3.01,  0.9 ,  0.  ,  4.4 ,  6.9 ,  8.2 ,  7.8 ,
        7.5 ,  6.2 ,  5.3 ,  4.9 ,  3.7 ,  1.05,  0.  ,  1.89,  4.6 ,
        8.6 ,  8.38,  7.54,  6.88,  5.78,  5.33,  4.19,  1.15,  0.  ,
        2.02,  5.63, 11.4 ,  9.33,  8.74,  7.56,  7.09,  5.9 ,  4.37,
        1.57,  0.  ,  1.29,  3.08,  6.44,  6.32,  5.53,  4.94,  4.02,
        3.46,  2.78,  0.92,  0.15,  0.85,  2.35,  5.02,  6.58,  7.09,
        6.66,  5.25,  4.39,  3.53,  1.15,  0.  ,  3.05,  3.05,  7.31,
        7.56,  6.59,  5.88,  4.73,  4.57,  3.  ,  1.25,  0.  ,  7.37,
        9.03,  7.14,  6.33,  5.66,  5.67,  4.24,  4.11,  3.16,  1.12,
        0.24,  2.89,  5.22,  6.41,  7.83, 10.21,  9.18,  8.02,  7.14,
        5.68,  2.42,  0.  ,  4.86,  7.24,  8.  ,  6.81,  5.87,  5.22,
        4.45,  3.62,  2.69,  0.86,  0.  ,  1.25,  3.96,  7.82,  9.72,
        9.75,  8.57,

### Slicing

To get a slice of data we use

ndarray[row_start:row_end, column_start:column_end]

*python is lower bound inclusive and upper bound exclusive*

To select the second, third and fourth rows

In [54]:
theoph[1:4, :]

array([[11.  , 79.6 ,  4.02,  0.25,  2.84],
       [11.  , 79.6 ,  4.02,  0.57,  6.57],
       [11.  , 79.6 ,  4.02,  1.12, 10.5 ]])

To select the first three columns

In [55]:
theoph[:, :3]

array([[11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [11.  , 79.6 ,  4.02],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 6.  , 72.4 ,  4.4 ],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 5.  , 70.5 ,  4.53],
       [ 7

To select the last eleven rows

In [56]:
theoph[-11:, :]

array([[ 9.  , 60.5 ,  5.3 ,  0.  ,  0.  ],
       [ 9.  , 60.5 ,  5.3 ,  0.25,  1.25],
       [ 9.  , 60.5 ,  5.3 ,  0.5 ,  3.96],
       [ 9.  , 60.5 ,  5.3 ,  1.  ,  7.82],
       [ 9.  , 60.5 ,  5.3 ,  2.  ,  9.72],
       [ 9.  , 60.5 ,  5.3 ,  3.52,  9.75],
       [ 9.  , 60.5 ,  5.3 ,  5.07,  8.57],
       [ 9.  , 60.5 ,  5.3 ,  7.07,  6.59],
       [ 9.  , 60.5 ,  5.3 ,  9.03,  6.11],
       [ 9.  , 60.5 ,  5.3 , 12.05,  4.57],
       [ 9.  , 60.5 ,  5.3 , 24.15,  1.17]])

Alternatively we can pass a list of the columns (or rows) we want

In [57]:
theoph[:, [1, 2, 4]]

array([[79.6 ,  4.02,  0.74],
       [79.6 ,  4.02,  2.84],
       [79.6 ,  4.02,  6.57],
       [79.6 ,  4.02, 10.5 ],
       [79.6 ,  4.02,  9.66],
       [79.6 ,  4.02,  8.58],
       [79.6 ,  4.02,  8.36],
       [79.6 ,  4.02,  7.47],
       [79.6 ,  4.02,  6.89],
       [79.6 ,  4.02,  5.94],
       [79.6 ,  4.02,  3.28],
       [72.4 ,  4.4 ,  0.  ],
       [72.4 ,  4.4 ,  1.72],
       [72.4 ,  4.4 ,  7.91],
       [72.4 ,  4.4 ,  8.31],
       [72.4 ,  4.4 ,  8.33],
       [72.4 ,  4.4 ,  6.85],
       [72.4 ,  4.4 ,  6.08],
       [72.4 ,  4.4 ,  5.4 ],
       [72.4 ,  4.4 ,  4.55],
       [72.4 ,  4.4 ,  3.01],
       [72.4 ,  4.4 ,  0.9 ],
       [70.5 ,  4.53,  0.  ],
       [70.5 ,  4.53,  4.4 ],
       [70.5 ,  4.53,  6.9 ],
       [70.5 ,  4.53,  8.2 ],
       [70.5 ,  4.53,  7.8 ],
       [70.5 ,  4.53,  7.5 ],
       [70.5 ,  4.53,  6.2 ],
       [70.5 ,  4.53,  5.3 ],
       [70.5 ,  4.53,  4.9 ],
       [70.5 ,  4.53,  3.7 ],
       [70.5 ,  4.53,  1.05],
       [72

We can also pass a list of boolean values to slice the array

This is know as a boolean mask

A common way to create a boolean mask is using the > < ==  operators on a column

Lets split the dataframe with all doses less than 4.1 mg/kg

In [58]:
mask = theoph[:, 2] < 4.1
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [59]:
theoph[mask, :]

array([[11.  , 79.6 ,  4.02,  0.  ,  0.74],
       [11.  , 79.6 ,  4.02,  0.25,  2.84],
       [11.  , 79.6 ,  4.02,  0.57,  6.57],
       [11.  , 79.6 ,  4.02,  1.12, 10.5 ],
       [11.  , 79.6 ,  4.02,  2.02,  9.66],
       [11.  , 79.6 ,  4.02,  3.82,  8.58],
       [11.  , 79.6 ,  4.02,  5.1 ,  8.36],
       [11.  , 79.6 ,  4.02,  7.03,  7.47],
       [11.  , 79.6 ,  4.02,  9.05,  6.89],
       [11.  , 79.6 ,  4.02, 12.12,  5.94],
       [11.  , 79.6 ,  4.02, 24.37,  3.28],
       [ 1.  , 80.  ,  4.  ,  0.  ,  0.  ],
       [ 1.  , 80.  ,  4.  ,  0.27,  1.29],
       [ 1.  , 80.  ,  4.  ,  0.58,  3.08],
       [ 1.  , 80.  ,  4.  ,  1.15,  6.44],
       [ 1.  , 80.  ,  4.  ,  2.03,  6.32],
       [ 1.  , 80.  ,  4.  ,  3.57,  5.53],
       [ 1.  , 80.  ,  4.  ,  5.  ,  4.94],
       [ 1.  , 80.  ,  4.  ,  7.  ,  4.02],
       [ 1.  , 80.  ,  4.  ,  9.22,  3.46],
       [ 1.  , 80.  ,  4.  , 12.1 ,  2.78],
       [ 1.  , 80.  ,  4.  , 23.85,  0.92],
       [ 8.  , 86.4 ,  3.1 ,  0.

## Vectorised operations

Numpy functions are vectorized. 

This means they are fast and efficient compared to base python

### Elementwise operations

For elementwise operators the same operation is applied to every element in the array

If we want to convert the weights from metric units to imperial (kg to lb)

We need to multiple every weight by 2.2

In base python we would write a loop or list comprehension

In numpy if is much simpler

In [60]:
theoph[:, 1] * 2.2

array([175.12, 175.12, 175.12, 175.12, 175.12, 175.12, 175.12, 175.12,
       175.12, 175.12, 175.12, 159.28, 159.28, 159.28, 159.28, 159.28,
       159.28, 159.28, 159.28, 159.28, 159.28, 159.28, 155.1 , 155.1 ,
       155.1 , 155.1 , 155.1 , 155.1 , 155.1 , 155.1 , 155.1 , 155.1 ,
       155.1 , 159.94, 159.94, 159.94, 159.94, 159.94, 159.94, 159.94,
       159.94, 159.94, 159.94, 159.94, 120.12, 120.12, 120.12, 120.12,
       120.12, 120.12, 120.12, 120.12, 120.12, 120.12, 120.12, 176.  ,
       176.  , 176.  , 176.  , 176.  , 176.  , 176.  , 176.  , 176.  ,
       176.  , 176.  , 142.12, 142.12, 142.12, 142.12, 142.12, 142.12,
       142.12, 142.12, 142.12, 142.12, 142.12, 155.1 , 155.1 , 155.1 ,
       155.1 , 155.1 , 155.1 , 155.1 , 155.1 , 155.1 , 155.1 , 155.1 ,
       190.08, 190.08, 190.08, 190.08, 190.08, 190.08, 190.08, 190.08,
       190.08, 190.08, 190.08, 128.04, 128.04, 128.04, 128.04, 128.04,
       128.04, 128.04, 128.04, 128.04, 128.04, 128.04, 143.  , 143.  ,
      

We can also muliply slices by slices

The dose is given in mg per kg.

To find out the mg given to each subject we multiply the dose column by the weight column

In [61]:
np.multiply(theoph[:, 1], theoph[:, 2])

array([319.992, 319.992, 319.992, 319.992, 319.992, 319.992, 319.992,
       319.992, 319.992, 319.992, 319.992, 318.56 , 318.56 , 318.56 ,
       318.56 , 318.56 , 318.56 , 318.56 , 318.56 , 318.56 , 318.56 ,
       318.56 , 319.365, 319.365, 319.365, 319.365, 319.365, 319.365,
       319.365, 319.365, 319.365, 319.365, 319.365, 319.88 , 319.88 ,
       319.88 , 319.88 , 319.88 , 319.88 , 319.88 , 319.88 , 319.88 ,
       319.88 , 319.88 , 319.956, 319.956, 319.956, 319.956, 319.956,
       319.956, 319.956, 319.956, 319.956, 319.956, 319.956, 320.   ,
       320.   , 320.   , 320.   , 320.   , 320.   , 320.   , 320.   ,
       320.   , 320.   , 320.   , 319.77 , 319.77 , 319.77 , 319.77 ,
       319.77 , 319.77 , 319.77 , 319.77 , 319.77 , 319.77 , 319.77 ,
       319.365, 319.365, 319.365, 319.365, 319.365, 319.365, 319.365,
       319.365, 319.365, 319.365, 319.365, 267.84 , 267.84 , 267.84 ,
       267.84 , 267.84 , 267.84 , 267.84 , 267.84 , 267.84 , 267.84 ,
       267.84 , 320.

np.multiply and the * operator are equivalent

Similarly there are functions for add, subtract, divide

And many more mathematical operations eg reciprocal, power, log / exp, sin / cos / tan

https://numpy.org/doc/stable/reference/routines.math.html

### Summary operations

There are many functions available that can summarise the data

These can be applied to the whole array

More commonly to every row or column

For example to find the minimum of each column, we specify axis=0

In [62]:
np.min(theoph, axis=0)

array([ 1. , 54.6,  3.1,  0. ,  0. ])

to find the mean of each row we specify axis=1

In [63]:
np.mean(theoph, axis=1)

array([19.072, 19.542, 20.352, 21.248, 21.26 , 21.404, 21.616, 21.824,
       22.112, 22.536, 24.454, 16.56 , 16.958, 18.246, 18.422, 18.61 ,
       18.63 , 18.78 , 19.046, 19.27 , 19.562, 21.6  , 16.006, 16.94 ,
       17.502, 17.85 , 17.97 , 18.23 , 18.262, 18.48 , 18.786, 19.176,
       21.05 , 16.82 , 17.268, 17.86 , 18.754, 18.922, 19.028, 19.2  ,
       19.38 , 19.69 , 20.054, 21.98 , 14.492, 14.956, 15.722, 16.972,
       16.762, 16.94 , 17.008, 17.314, 17.492, 17.766, 19.676, 17.   ,
       17.312, 17.732, 18.518, 18.67 , 18.82 , 18.988, 19.204, 19.536,
       19.976, 21.954, 14.34 , 14.53 , 14.88 , 15.518, 16.03 , 16.424,
       16.642, 16.756, 16.988, 17.426, 19.384, 15.606, 16.266, 16.32 ,
       17.264, 17.522, 17.63 , 17.792, 17.982, 18.334, 18.626, 20.68 ,
       19.5  , 21.034, 21.432, 21.138, 21.17 , 21.338, 21.638, 21.782,
       22.082, 22.452, 24.61 , 14.788, 15.392, 15.938, 16.226, 16.716,
       17.492, 17.586, 17.76 , 18.044, 18.296, 19.964, 14.784, 15.806,
      

To sum up the numbers in the whole array we leave out the axis arguement

We can nest functions in numpy

Here we round to one decimal place

In [64]:
np.round(np.sum(theoph), 1)

12086.5

plus many more arithmetic operations available

### Linear algebra

numpy also contains functions for many common linear algebra functions

https://numpy.org/doc/stable/reference/routines.linalg.html

Matrix multiplication

In [65]:
np.matmul(theoph[:2, :], theoph[:5, :2])

array([[1048.96 , 7590.656],
       [1074.81 , 7777.716]])

eigenvalues

In [66]:
np.linalg.eig(theoph[:5, :])

(array([ 9.78998626e+01,  8.38897366e+00, -8.88836233e-01, -1.14252115e-15,
        -4.90619604e-16]),
 array([[-4.17368737e-01, -1.99891890e-01,  2.05229022e-01,
          8.21151140e-01,  1.04006162e-01],
        [-4.28646806e-01, -1.49324302e-02, -7.19385779e-03,
         -1.41399350e-01,  3.58233166e-02],
        [-4.48083801e-01,  3.03883884e-01, -4.99039276e-01,
          5.52916837e-01, -9.93931290e-01],
        [-4.69583906e-01,  6.56450108e-01, -8.20725225e-01,
         -5.55117026e-16, -5.89701326e-16],
        [-4.69869252e-01,  6.60717864e-01,  1.87614504e-01,
         -9.25195044e-17, -4.90649931e-16]]))

### Manipulating arrays

We can stack arrays together to add extra rows or columns

https://numpy.org/doc/stable/reference/routines.ma.html

In [67]:
new_array = np.hstack([theoph, theoph])
new_array

array([[11.  , 79.6 ,  4.02, ...,  4.02,  0.  ,  0.74],
       [11.  , 79.6 ,  4.02, ...,  4.02,  0.25,  2.84],
       [11.  , 79.6 ,  4.02, ...,  4.02,  0.57,  6.57],
       ...,
       [ 9.  , 60.5 ,  5.3 , ...,  5.3 ,  9.03,  6.11],
       [ 9.  , 60.5 ,  5.3 , ...,  5.3 , 12.05,  4.57],
       [ 9.  , 60.5 ,  5.3 , ...,  5.3 , 24.15,  1.17]])

In [68]:
new_array.shape

(132, 10)

In [69]:
new_array = np.vstack([theoph, theoph])
new_array.shape

(264, 5)

In [70]:
new_array = np.hstack([theoph, theoph[:, 1] * 2.2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [71]:
theoph.shape

(132, 5)

In [72]:
theoph[:, 1].shape

(132,)

In [73]:
theoph[:, 1:2].shape

(132, 1)

In [74]:
new_array = np.hstack([theoph, theoph[:, 1:2] * 2.2])
new_array

array([[1.1000e+01, 7.9600e+01, 4.0200e+00, 0.0000e+00, 7.4000e-01,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 2.5000e-01, 2.8400e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 5.7000e-01, 6.5700e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 1.1200e+00, 1.0500e+01,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 2.0200e+00, 9.6600e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 3.8200e+00, 8.5800e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 5.1000e+00, 8.3600e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 7.0300e+00, 7.4700e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 9.0500e+00, 6.8900e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 1.2120e+01, 5.9400e+00,
        1.7512e+02],
       [1.1000e+01, 7.9600e+01, 4.0200e+00, 2.4370e+01, 3.2800e+00,
        1.7512e+02],
       [6.0000e+00, 7