# Numpy Exercises

### Exercise 1:

Read in the theoph.csv data

**reminder** columns are: *Subject, Wt, Dose, Time, conc*

In [1]:
import numpy as np
theoph_file_location = 'theoph.csv'
theoph = np.genfromtxt(theoph_file_location, delimiter=',', skip_header=1)
theoph

array([[  nan,   nan,   nan,   nan,   nan],
       [11.  , 79.6 ,  4.02,  0.  ,  0.74],
       [11.  , 79.6 ,  4.02,  0.25,  2.84],
       [11.  , 79.6 ,  4.02,  0.57,  6.57],
       [11.  , 79.6 ,  4.02,  1.12, 10.5 ],
       [11.  , 79.6 ,  4.02,  2.02,  9.66],
       [11.  , 79.6 ,  4.02,  3.82,  8.58],
       [11.  , 79.6 ,  4.02,  5.1 ,  8.36],
       [11.  , 79.6 ,  4.02,  7.03,  7.47],
       [11.  , 79.6 ,  4.02,  9.05,  6.89],
       [11.  , 79.6 ,  4.02, 12.12,  5.94],
       [11.  , 79.6 ,  4.02, 24.37,  3.28],
       [ 6.  , 72.4 ,  4.4 ,  0.  ,  0.  ],
       [ 6.  , 72.4 ,  4.4 ,  0.27,  1.72],
       [ 6.  , 72.4 ,  4.4 ,  0.52,  7.91],
       [ 6.  , 72.4 ,  4.4 ,  1.  ,  8.31],
       [ 6.  , 72.4 ,  4.4 ,  1.92,  8.33],
       [ 6.  , 72.4 ,  4.4 ,  3.5 ,  6.85],
       [ 6.  , 72.4 ,  4.4 ,  5.02,  6.08],
       [ 6.  , 72.4 ,  4.4 ,  7.03,  5.4 ],
       [ 6.  , 72.4 ,  4.4 ,  9.  ,  4.55],
       [ 6.  , 72.4 ,  4.4 , 12.  ,  3.01],
       [ 6.  , 72.4 ,  4.4 , 24.

### Exercise 2:

The data is approximately linear between one hour and 12 hours. We are going to work with just this data for now.

Create a set of data that only includes rows where time is greater than 0.9 and less than 13.

In [2]:
mask = (theoph[:, 3] > 0.9) & (theoph[:, 3] < 13)
data = theoph[mask, :]
data

array([[11.  , 79.6 ,  4.02,  1.12, 10.5 ],
       [11.  , 79.6 ,  4.02,  2.02,  9.66],
       [11.  , 79.6 ,  4.02,  3.82,  8.58],
       [11.  , 79.6 ,  4.02,  5.1 ,  8.36],
       [11.  , 79.6 ,  4.02,  7.03,  7.47],
       [11.  , 79.6 ,  4.02,  9.05,  6.89],
       [11.  , 79.6 ,  4.02, 12.12,  5.94],
       [ 6.  , 72.4 ,  4.4 ,  1.  ,  8.31],
       [ 6.  , 72.4 ,  4.4 ,  1.92,  8.33],
       [ 6.  , 72.4 ,  4.4 ,  3.5 ,  6.85],
       [ 6.  , 72.4 ,  4.4 ,  5.02,  6.08],
       [ 6.  , 72.4 ,  4.4 ,  7.03,  5.4 ],
       [ 6.  , 72.4 ,  4.4 ,  9.  ,  4.55],
       [ 6.  , 72.4 ,  4.4 , 12.  ,  3.01],
       [ 5.  , 70.5 ,  4.53,  1.02,  8.2 ],
       [ 5.  , 70.5 ,  4.53,  2.02,  7.8 ],
       [ 5.  , 70.5 ,  4.53,  3.62,  7.5 ],
       [ 5.  , 70.5 ,  4.53,  5.08,  6.2 ],
       [ 5.  , 70.5 ,  4.53,  7.07,  5.3 ],
       [ 5.  , 70.5 ,  4.53,  9.  ,  4.9 ],
       [ 5.  , 70.5 ,  4.53, 12.15,  3.7 ],
       [ 7.  , 72.7 ,  4.4 ,  1.07,  8.6 ],
       [ 7.  , 72.7 ,  4.4 ,  2.

**Use the cut down data set from 0.9 hours to 13 hours that you created in exercise 2, for the rest of the exercises.**

### Exercise 3:

For subject 4 find:

* the maximum concentration of the drug
* the time at which the maximum concentration occurs
* the minimum concentration of the drug
* the time at which the minimum concentration occurs
* save these values and the subject number in an array

In [15]:
# select subject 4
four_mask = data[:, 0] == 4
four_data = data[four_mask, :]

# max concentration
max_con = np.max(four_data[:, 4])
max_con_idx = np.argmax(four_data[:, 4])
time_of_max_con = four_data[max_con_idx, 3]

# min concentration
min_con = np.min(four_data[:, 4])
min_con_idx = np.argmin(four_data[:, 4])
time_of_min_con = four_data[min_con_idx, 3]

# save
min_max_subject_arr = np.array([4, max_con, time_of_max_con, min_con, time_of_min_con])
min_max_subject_arr

array([ 4.  ,  8.  ,  0.98,  2.69, 12.12])

### Exercise 4:

Repeat the steps in exercise 3 for all subjects. Create a summary array, with a row for each subject and columns containing:
* subject
* maximum concentration of drug
* time at which maximum concentration occurs 
* minimum concentration of drug 
* time at which minimum concentration occurs

In [37]:
def make_summary_row(subject):
    subject_mask = data[:, 0] == subject
    subject_data = data[subject_mask, :]
    con_col = subject_data[:, 4]

    # max concentration
    max_con = np.max(con_col)
    time_of_max_con = subject_data[np.argmax(con_col), 3]

    # min concentration
    min_con = np.min(con_col)
    time_of_min_con = subject_data[np.argmin(con_col), 3]

    return np.array([subject, max_con, time_of_max_con, min_con, time_of_min_con])

num_subjects = np.unique(data[:, 0]).size
summary_rows = np.array([make_summary_row(idx+1) for idx in range(num_subjects)])
summary_rows

array([[ 1.  ,  6.44,  1.15,  2.78, 12.1 ],
       [ 2.  ,  7.09,  3.48,  3.53, 12.05],
       [ 3.  ,  7.56,  2.02,  3.  , 12.1 ],
       [ 4.  ,  8.  ,  0.98,  2.69, 12.12],
       [ 5.  ,  8.2 ,  1.02,  3.7 , 12.15],
       [ 6.  ,  8.33,  1.92,  3.01, 12.  ],
       [ 7.  ,  8.6 ,  1.07,  4.19, 11.98],
       [ 8.  ,  7.14,  1.05,  3.16, 11.6 ],
       [ 9.  ,  9.75,  3.52,  4.57, 12.05],
       [10.  , 10.21,  3.55,  5.68, 12.1 ],
       [11.  , 10.5 ,  1.12,  5.94, 12.12],
       [12.  , 11.4 ,  1.  ,  4.37, 12.  ]])

### Exercise 5:

Using the summary data created in exercise 4, find:

* mean of the maximum concentrations (max conc)
* mean of the times at which maximum concentration occurs (max time)
* mean of the minimum concentrations (min conc)
* mean of the times at which minimum concentration occurs (min time)

In [41]:
# note - converting the array to a tuple allow it to be broken up into variables
mean_summary = np.mean(summary_rows[:, 1:], axis=0)
cmax, tmax, cmin, tmin = tuple(mean_summary)
print(cmax, tmax, cmin, tmin)

8.601666666666667 1.8233333333333335 3.885 12.030833333333332


### Exercise 6:

If we plotted a scatter plot with time on the x axis and concentration on the y axis, the data would be roughly linear.

A line approximately fitting the data is defined by the two points (max time, max conc) and (min time, min conc) calculated in the previous step. 

Workout the gradient and intercept of the line.

In [42]:
gradient = (cmax - cmin) / (tmax - tmin)
intercept = cmax - gradient * tmax
print(f"y = {gradient}x + {intercept}")

y = -0.4620785370234306x + 9.44418986583939
